<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260725181602 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE balance (id UUID NOT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE category (id UUID NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE expense (received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, description VARCHAR(255) DEFAULT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, category_id UUID DEFAULT NULL, balance_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA612469DE2 ON expense (category_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6AE91A3DD ON expense (balance_id)');
        $this->addSql('CREATE TABLE expense_attachment (id UUID NOT NULL, media_ref_key UUID NOT NULL, expense_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C94BE6B2F395DB7B ON expense_attachment (expense_id)');
        $this->addSql('CREATE INDEX IDX_C94BE6B22FB8E97E ON expense_attachment (media_ref_key)');
        $this->addSql('CREATE TABLE fund (id UUID NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE income (id UUID NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, fund_id UUID DEFAULT NULL, balance_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FA862D025A38F89 ON income (fund_id)');
        $this->addSql('CREATE INDEX IDX_3FA862D0AE91A3DD ON income (balance_id)');
        $this->addSql('CREATE TABLE media (id UUID NOT NULL, storage_key VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA612469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6AE91A3DD FOREIGN KEY (balance_id) REFERENCES balance (id)');
        $this->addSql('ALTER TABLE expense_attachment ADD CONSTRAINT FK_C94BE6B2F395DB7B FOREIGN KEY (expense_id) REFERENCES expense (id)');
        $this->addSql('ALTER TABLE expense_attachment ADD CONSTRAINT fk_expense_attachment_file FOREIGN KEY (media_ref_key) REFERENCES media (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE income ADD CONSTRAINT FK_3FA862D025A38F89 FOREIGN KEY (fund_id) REFERENCES fund (id)');
        $this->addSql('ALTER TABLE income ADD CONSTRAINT FK_3FA862D0AE91A3DD FOREIGN KEY (balance_id) REFERENCES balance (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA612469DE2');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6AE91A3DD');
        $this->addSql('ALTER TABLE expense_attachment DROP CONSTRAINT FK_C94BE6B2F395DB7B');
        $this->addSql('ALTER TABLE expense_attachment DROP CONSTRAINT fk_expense_attachment_file');
        $this->addSql('ALTER TABLE income DROP CONSTRAINT FK_3FA862D025A38F89');
        $this->addSql('ALTER TABLE income DROP CONSTRAINT FK_3FA862D0AE91A3DD');
        $this->addSql('DROP TABLE balance');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE expense_attachment');
        $this->addSql('DROP TABLE fund');
        $this->addSql('DROP TABLE income');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE "user"');
    }
}
