<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628184533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE balance (id VARCHAR(255) NOT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE category (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE expense (id VARCHAR(255) NOT NULL, media JSON NOT NULL, description VARCHAR(255) DEFAULT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, category_id VARCHAR DEFAULT NULL, balance_id VARCHAR DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2d3a8da612469de2 ON expense (category_id)');
        $this->addSql('CREATE INDEX idx_2d3a8da6ae91a3dd ON expense (balance_id)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT fk_2d3a8da612469de2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT fk_2d3a8da6ae91a3dd FOREIGN KEY (balance_id) REFERENCES balance (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE fund (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE income (id VARCHAR(255) NOT NULL, amount_minors INT NOT NULL, amount_currency VARCHAR(255) NOT NULL, fund_id VARCHAR DEFAULT NULL, balance_id VARCHAR DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3fa862d025a38f89 ON income (fund_id)');
        $this->addSql('CREATE INDEX idx_3fa862d0ae91a3dd ON income (balance_id)');
        $this->addSql('ALTER TABLE income ADD CONSTRAINT fk_3fa862d025a38f89 FOREIGN KEY (fund_id) REFERENCES fund (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE income ADD CONSTRAINT fk_3fa862d0ae91a3dd FOREIGN KEY (balance_id) REFERENCES balance (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649f85e0677 ON "user" (username)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "balance"');
        $this->addSql('DROP TABLE "category"');
        $this->addSql('DROP TABLE "expense"');
        $this->addSql('DROP TABLE "fund"');
        $this->addSql('DROP TABLE "income"');
        $this->addSql('DROP TABLE "user"');
    }
}
